kind: pipeline
name: default

steps:
- name: test
  image: golang:1.22.2
  volumes:
  - name: deps
    path: /go
  commands:
  - go test ./... -cover -coverprofile coverage.out
  when:
    event:
      exclude:
      - tag

- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token:
      from_secret: CODECOV_TOKEN
  when:
    event:
      exclude:
      - tag

- name: build api
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kgantsov/dlock
    context: .
    dockerfile: ./Dockerfile
    auto_tag: true